GET http://localhost:30019/tourEntity/5fb8e358-f108-4f9d-b4f2-674bc2fd6723
Accept: application/json

###
###
POST http://localhost:30019/tour/save
Content-Type: application/json

{
    "name": "tourOne",
    "description": "this is my first tourEntity!",
    "startingPoint": "here",
    "destination": "there",
    "distance": 2
}


